version: "3.7"

services:
    infovis:
      environment:
        - FLASK_ENV=development
        - ENV_DOCKER_REGISTRY_HOST=localhost
        - ENV_DOCKER_REGISTRY_PORT=5000
      build: ./InfoVis-Framework-2021
      # restart: always
      # network_mode: host
      ports: 
      - "5000:5000"
      # command: python3 run.py
      command: gunicorn run:app -b 0.0.0.0:5000 --worker-class gevent
      
      # "-" --capture-output --timeout 600 --log-level DEBUG -b 127.0.0.1:5000

